local _ = require("bookends_i18n").gettext

-- v5 token picker: descriptive names only. Legacy single-letter tokens still
-- resolve at runtime via the alias table in bookends_tokens.lua, but they are
-- not documented surface and not inserted by the picker.
return {
    { _("Metadata"), {
        { "%title", _("Document title") },
        { "%author", _("Author(s)") },
        { "%series", _("Series with index (combined)") },
        { "%series_name", _("Series name only") },
        { "%series_num", _("Series number only") },
        { "%chap_title", _("Chapter title (deepest)") },
        { "%chap_title_1", _("Chapter title at depth 1") },
        { "%chap_title_2", _("Chapter title at depth 2") },
        { "%chap_title_3", _("Chapter title at depth 3") },
        { "%chap_num", _("Current chapter number") },
        { "%chap_count", _("Total chapter count") },
        { "%filename", _("File name") },
        { "%lang", _("Book language") },
        { "%format", _("Document format (EPUB, PDF, etc.)") },
        { "%highlights", _("Number of highlights") },
        { "%notes", _("Number of notes") },
        { "%bookmarks", _("Number of bookmarks") },
        { "%annotations", _("Total annotations (bookmarks + highlights + notes)") },
    }},
    { _("Page / progress"), {
        { "%page_num", _("Current page number") },
        { "%page_count", _("Total pages") },
        { "%book_pct", _("Book percentage read") },
        { "%chap_pct", _("Chapter percentage read") },
        { "%chap_read", _("Pages read in chapter") },
        { "%chap_pages", _("Total pages in chapter") },
        { "%chap_pages_left", _("Pages left in chapter") },
        { "%pages_left", _("Pages left in book") },
    }},
    { _("Progress bars"), {
        { "%bar", _("Progress bar (configure type in line editor)") },
        { "%bar{100}", _("Fixed-width progress bar (100px)") },
        { "%bar{v10}", _("Progress bar, 10px tall") },
        { "%bar{100v10}", _("Progress bar, 100px × 10px") },
    }},
    { _("Time / date"), {
        { "%time", _("Current time (24h, same as %time_24h)") },
        { "%time_12h", _("Current time (12-hour)") },
        { "%time_24h", _("Current time (24-hour)") },
        { "%date", _("Short date (e.g. 23 Apr)") },
        { "%date_long", _("Long date (e.g. 23 April 2026)") },
        { "%date_numeric", _("Numeric date (dd/mm/yyyy)") },
        { "%weekday", _("Weekday name (e.g. Thursday)") },
        { "%weekday_short", _("Short weekday (e.g. Thu)") },
        { "%datetime{%d %B}", _("Custom date/time format (strftime spec)") },
        { "%chap_time_left", _("Estimated time left in chapter") },
        { "%book_time_left", _("Estimated time left in book") },
    }},
    { _("Session / reading"), {
        { "%session_time", _("Session reading time") },
        { "%session_pages", _("Pages read this session") },
        { "%speed", _("Reading speed (pages/hour)") },
        { "%book_read_time", _("Total time spent reading this book") },
    }},
    { _("Device"), {
        { "%batt", _("Battery level (percentage)") },
        { "%batt_icon", _("Battery level (icon)") },
        { "%wifi", _("Wi-Fi status (icon)") },
        { "%light", _("Frontlight intensity") },
        { "%warmth", _("Frontlight warmth") },
        { "%invert", _("Page-turn-inverted indicator") },
        { "%mem", _("System memory usage (percentage)") },
        { "%ram", _("KOReader process RAM usage (MB)") },
        { "%disk", _("Free disk space (GB)") },
    }},
}
